apiVersion: kzed.io/v1alpha1
kind: SequentialDataSet
metadata:
  labels:
    app.kubernetes.io/name: kzed
    app.kubernetes.io/managed-by: kustomize
  name: sequentialdataset-sample
spec:
  # TODO(user): Add fields here
